server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/luocong2013/spring-cloud-config
          search-paths: repo
          default-label: master
          username: luocong2013
          password: aA13378215903
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
