server:
  port: 7077

spring:
  mail:
    host: smtp.sina.com
    port: 587
    username: xx@sina.com
    password: xx
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
