spring:
  application:
    name: gateway-zuul
  redis:
    database: 0
    host: 192.168.0.110
    port: 6379
    password:
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 5000
server:
  port: 8730
  tomcat:
    # 最大worker线程数，默认200
    max-threads: 400
    # 最小worker线程，默认10
    min-spare-threads: 20
  undertow:
    # IO线程数，默认为CPU核心数，最小为2
    io-threads: 8
    # 阻塞任务线程池，值设置取决于系统的负载，默认为io-threads * 8
    worker-threads: 40
    # 每块buffer的空间大小
    buffer-size: 512
    # 是否分配的直接内存
    direct-buffers: true
eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 30
  client:
    # 检查健康
    healthcheck:
      enabled: true
    service-url:
      # eureka server 集群
      # defaultZone: http://127.0.0.1:8762/eureka/,http://127.0.0.1:8763/eureka/
      # eureka 单机
      defaultZone: http://luocong:pwd123456@127.0.0.1:8761/eureka/
ribbon:
  http:
    client:
      enabled: true
  okhttp:
    enabled: true
  # 从eureka获取服务列表信息
  eureka:
    enabled: true
zuul:
  prefix: /api
  # 忽略所有微服务，只路由指定微服务
  ignored-services: "*"
  # 过滤敏感头信息，默认会过滤掉HTTP请求头信息中的一些敏感信息，防止这些敏感的头信息传递到下游外部服务器，默认如下
  # 可以设置为空来覆盖默认值
  sensitive-headers: Cookie,Set-Cookie,Authorization
  host:
    # 目标主机的最大连接数，默认200
    max-total-connections: 400
    # 每个主机的初始连接数，默认值为20
    max-per-route-connections: 40
    socket-timeout-millis: 200
    connect-timeout-millis: 50
    time-unit: seconds
  routes:
    # 路由到微服务
    service-consumer:
      path: /consumer/**
      serviceId: service-consumer
    service-consumer-hystrix:
      path: /hystrix/**
      serviceId: service-consumer-hystrix
    # 静态路由
    static:
      path: /static
      url: http://www.163.com/
    # 跳转路由，注意：path必须和@RequestMapping中的一致，这里的local
    local:
      path: /local/**
      url: forward:/local
  # 限流
  ratelimit:
    enabled: true
    repository: redis
    behind-proxy: true
    add-response-headers: true
    default-policy-list:
      - limit: 10
        quota: 1000
        refresh-interval: 60
        type:
          - user
          - origin
          - url
          - httpmethod
    policy-list:
      # 限制每分钟最多请求3次
      service-consumer:
        - limit: 3
          quota: 1000
          refresh-interval: 60
          type:
            - user
            - origin
            - url
#        - type:
#            - user=anonymous
#            - origin=zync.com
#            - url=/api
#            - role=user
#            - httpmethod=get