spring:
  application:
    name: gateway-zuul
server:
  port: 8730
  tomcat:
    # 最大worker线程数，默认200
    max-threads: 400
    # 最小worker线程，默认10
    min-spare-threads: 20
  undertow:
    # IO线程数，默认为CPU核心数，最小为2
    io-threads: 8
    # 阻塞任务线程池，值设置取决于系统的负载，默认为io-threads * 8
    worker-threads: 40
    # 每块buffer的空间大小
    buffer-size: 512
    # 是否分配的直接内存
    direct-buffers: true
eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 30
  client:
    # 检查健康
    healthcheck:
      enabled: true
    service-url:
      # eureka server 集群
      # defaultZone: http://127.0.0.1:8762/eureka/,http://127.0.0.1:8763/eureka/
      # eureka 单机
      defaultZone: http://luocong:pwd123456@127.0.0.1:8761/eureka/
ribbon:
  http:
    client:
      enabled: true
  okhttp:
    enabled: true
  # 从eureka获取服务列表信息
  eureka:
    enabled: true
zuul:
  prefix: /api
  # 过滤敏感头信息，默认会过滤掉HTTP请求头信息中的一些敏感信息，防止这些敏感的头信息传递到下游外部服务器
  sensitive-headers: Cookie,Set-Cookie,Authorization
  host:
    # 目标主机的最大连接数，默认200
    max-total-connections: 400
    # 每个主机的初始连接数，默认值为20
    max-per-route-connections: 40
    socket-timeout-millis: 200
    connect-timeout-millis: 50
    time-unit: seconds
  routes:
    # 路由到微服务
    service-consumer:
      path: /consumer/**
      serviceId: service-consumer
    service-consumer-hystrix:
      path: /hystrix/**
      serviceId: service-consumer-hystrix
    # 静态路由
    static:
      path: /static
      url: http://www.163.com/
    # 跳转路由
    local:
      path: /local/**
      url: forward:/zuul