spring:
  application:
    name: gateway-zuul
server:
  port: 8730
eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 30
  client:
    # 检查健康
    healthcheck:
      enabled: true
    service-url:
      # eureka server 集群
      # defaultZone: http://127.0.0.1:8762/eureka/,http://127.0.0.1:8763/eureka/
      # eureka 单机
      defaultZone: http://luocong:pwd123456@127.0.0.1:8761/eureka/
ribbon:
  http:
    client:
      enabled: true
  okhttp:
    enabled: true
zuul:
  prefix: /api
  host:
    max-total-connections: 400
    max-per-route-connections: 40
    socket-timeout-millis: 20
    connect-timeout-millis: 5
    time-unit: seconds
  routes:
    service-consumer:
      path: /consumer/**
      serviceId: service-consumer
    service-consumer-hystrix:
      path: /hystrix/**
      serviceId: service-consumer-hystrix
