version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis_1.0.0
    ports:
      - 6379:6379
    restart: "no"
    networks:
      mynetwork:
        aliases:
          - redis
    volumes:
      - $PWD/data:/data
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
networks:
  mynetwork:
    driver: bridge