server:
  port: 10004
spring:
  application:
    name: spring-boot-ai-rag-simple
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}


logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG
