spring:
  application:
    name: ibed
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB
  thymeleaf:
    cache: false

server:
  port: 7070
  servlet:
    context-path: /ibed