# 数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.100:3306/ssm?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    hikari:
      connection-test-query: SELECT 1
      read-only: false
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 15
      minimum-idle: 10

# MyBatis配置
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.zync.ibed.po
  # 检查MyBatis配置文件是否存在
  # check-config-location: true
  # config-location: classpath:mybatis/mybatis.cfg.xml
  # 以下可以替换配置文件
  configuration:
    cache-enabled: true
    lazy-loading-enabled: false
    default-statement-timeout: 3000
    local-cache-scope: statement
    default-executor-type: simple
    map-underscore-to-camel-case: true
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 通用Mapper配置
mapper:
  mappers:
    - com.zync.ibed.utils.CustomMapper
  not-empty: false
  identity: MYSQL

# Minio的配置，这是一个用于开发测试的 minio 地址.
minio:
  tieba:
    endpoint: http://192.168.0.111:9000
    access-key: dev
    secret-key: 123456789
    bucket: tieba
