server:
  port: 9000
spring:
  application:
    name: authorization-server
  h2:
    console:
      # 开启console 访问 默认false
      enabled: true
      settings:
        # 允许console 远程访问 默认false
        web-allow-others: true
        # 开启h2 console 跟踪 方便调试  默认 false
        trace: true
        web-admin-password: 123456
      # h2 访问路径上下文
      path: /h2-console

# 方便调试
logging:
  level:
    org.springframework.web: trace
    org.springframework.security: debug
    org.springframework.security.oauth2: debug