spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study?useUnicode=true&characterEncoding=utf8
    username: root
    password: 1qaz2wsx
    hikari:
      minimum-idle: 2
      maximum-pool-size: 2
      validation-timeout: 2500
      connection-test-query: select 1
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        #useLocalTransactionState: true #这个配置移除事务才起作用
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false

mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
  type-aliases-package: com.zync.**.entity
  type-enums-package: com.zync.**.enums
  # 检查MyBatis配置文件是否存在
  # check-config-location: true
  # config-location: classpath:mybatis/mybatis.cfg.xml
  # 以下可以替换配置文件
  configuration:
    cache-enabled: true
    lazy-loading-enabled: false
    default-statement-timeout: 3000
    local-cache-scope: statement
    default-executor-type: simple
    # 下滑线转驼峰
    map-underscore-to-camel-case: true
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      logic-delete-field: "deleted" #全局逻辑删除字段
      logic-not-delete-value: "0" #全局逻辑未删除值
      logic-delete-value: "UNIX_TIMESTAMP()" #全局逻辑删除值，时间戳函数，精确到毫秒


