# Version: 7.3.0

FROM elasticsearch:7.3.0

MAINTAINER luocong2017<luocong2017@gmail.com>

RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
         echo 'Asia/Shanghai' > /etc/timezone
		
COPY config /usr/share/elasticsearch/config
COPY plugins /usr/share/elasticsearch/plugins