#Version: 1.0.1
FROM alpine:latest

MAINTAINER luocong<luocong@thunisoft.com>

EXPOSE 9466

WORKDIR /opt

RUN echo "http://mirrors.aliyun.com/alpine/latest-stable/main/" > /etc/apk/repositories && \
		 echo "http://mirrors.aliyun.com/alpine/latest-stable/community/" >> /etc/apk/repositories && \
		 apk --update add tzdata && \
		 cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
		 echo 'Asia/Shanghai' > /etc/timezone && \
		 apk del tzdata && \
		 apk add openjdk8-jre && \
		 apk add --update ttf-dejavu fontconfig && \
		 rm -rf /var/cache/apk/*

COPY image-sign.jar /opt/image-sign.jar

COPY simsun.ttc /usr/share/fonts/chinese/simsun.ttc

ENV LC_ALL zh_CN.UTF-8

ENTRYPOINT ["sh", "-c", "java $PARAMS -Djava.security.egd=file:/dev/./urandom -jar image-sign.jar"]