# Version: 7.3.0

FROM kibana:7.3.0

MAINTAINER luocong2017<luocong2017@gmail.com>

USER root:root

RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo 'Asia/Shanghai' > /etc/timezone

USER kibana