#Version: 3.7.3
FROM alpine:latest

MAINTAINER luocong2017<luocong2017@gmail.com>

RUN echo "http://mirrors.aliyun.com/alpine/latest-stable/main/" > /etc/apk/repositories && \
		 echo "http://mirrors.aliyun.com/alpine/latest-stable/community/" >> /etc/apk/repositories && \
		 apk update && \
		 apk upgrade && \
		 apk add --upgrade tzdata && \
		 cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
		 echo 'Asia/Shanghai' > /etc/timezone && \
		 apk del tzdata && \
		 apk add --no-cache python3 python3-dev gcc openssl-dev openssl libressl libc-dev linux-headers libffi-dev libxml2-dev libxml2 libxslt-dev openssh-client openssh-sftp-server && \
		 pip3 install --default-timeout=100 --no-cache-dir --upgrade pip setuptools pymongo pymysql elasticsearch minio requests Scrapy && \
		 rm -rf /var/cache/apk/*

ENV LC_ALL zh_CN.UTF-8