spring:
  application:
    name: turbine-server
server:
  port: 8720
eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    # 检查健康
    healthcheck:
      enabled: true
    service-url:
      # eureka server 集群
      # defaultZone: http://127.0.0.1:8762/eureka/,http://127.0.0.1:8763/eureka/
      # eureka 单机
      defaultZone: http://luocong:pwd123456@127.0.0.1:8761/eureka/
turbine:
  aggregator:
    # 指定聚合那些集群“,”分割，默认为default
    cluster-config: default
  # 配置Eurake中的serviceId列表，表明监控那些服务
  app-config: service-consumer-hystrix
  cluster-name-expression: "'default'"
  combine-host-port: true
management:
  endpoints:
    web:
      exposure:
        include: "*"