server:
  port: 9002
spring:
  application:
    name: spring-boot-ai-author-mcp-client
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
    mcp:
      client:
        enabled: true
        name: mcp-client
        version: 1.0.0
        type: SYNC
        request-timeout: 30s
        stdio:
          servers-configuration: classpath:/mcp-servers-config.json
#        sse:
#          connections:
#            url: http://localhost:9001


logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG

#debug: true
