# Version: 1.0.0
FROM registry.cn-hangzhou.aliyuncs.com/cuit-luoc/python:3.7.3

MAINTAINER luocong2017<luocong2017@gmail.com>

COPY code /opt/

WORKDIR /opt/Baike/Baike

ENTRYPOINT ["sh", "-c", "python3 run.py"]