version: '3'
services:
  minio:
    image: jpillora/dnsmasq
    container_name: dns-server
    ports:
      - "53:53/udp"
      - "5380:8080"
    restart: always
    networks:
      mynetwork:
        aliases:
          - dns-server
    environment:
      TZ: Asia/Shanghai
      HTTP_USER: admin
      HTTP_PASS: admin
    volumes:
      - $PWD/dnsmasq.conf:/etc/dnsmasq.conf
      - $PWD/dnsmasq.d/:/etc/dnsmasq.d/
networks:
  mynetwork:
    driver: bridge
