server:
  port: 10002
spring:
  application:
    name: spring-boot-ai-ollama-chat
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:7b


logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG
