server:
  port: 8090

logging:
  level:
    org.springframework.web: trace
    org.springframework.security: debug
    org.springframework.security.oauth2: debug

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          # provider 尽量用域名 不要用localhost 一定不要用IP 而且要和well-known接口中保持一致
          issuer-uri: http://auth-server:9000