version: '3'
services:
    nginx:
        image: nginx:1.21.3
        container_name: nginx-server
        ports:
            - 80:80
        restart: always
        networks:
            - docker-nginx-network
        volumes:
            - $PWD/nginx.conf:/etc/nginx/nginx.conf
            - $PWD/conf.d/:/etc/nginx/conf.d/
            - $PWD/logs/:/var/log/nginx/
            - $PWD/web/:/opt/nginx/web/
networks:
    docker-nginx-network:
        driver: bridge
