spring:
  application:
    name: service-consumer-hystrix
server:
  port: 8742
eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 30
  client:
    # \u68C0\u67E5\u5065\u5EB7
    healthcheck:
      enabled: true
    service-url:
      # eureka server \u96C6\u7FA4
      # defaultZone: http://127.0.0.1:8762/eureka/,http://127.0.0.1:8763/eureka/
      # eureka \u5355\u673A
      defaultZone: http://luocong:pwd123456@127.0.0.1:8761/eureka/
# Feign\u5168\u5C40\u5173\u95ED/\u5F00\u542FHystrix\u652F\u6301
feign:
  hystrix:
    enabled: true