version: '3.8'
services:
    dbmaster:
        image: mysql:latest
        container_name: dbmaster
        ports:
            - 13306:3306
        restart: "no"
        networks:
            mynetwork:
                aliases:
                    - dbmaster
        environment:
            MYSQL_ROOT_PASSWORD: root
            TZ: Asia/Shanghai
        volumes:
            - $PWD/log:/var/log/mysql
            - $PWD/mysql-files:/var/lib/mysql-files
            - $PWD/data:/var/lib/mysql
networks:
    mynetwork:
        driver: bridge