version: '3'
services:
    minio:
        image: minio/minio
        container_name: minio_1.0.0
        ports:
            - 9000:9000
        restart: always
        networks:
            mynetwork:
                aliases:
                    - minio
        environment:
            MINIO_ACCESS_KEY: root
            MINIO_SECRET_KEY: 123456789
        volumes:
            - $PWD/data:/data
        command:
            minio server /data --address ':9000'
networks:
    mynetwork:
        driver: bridge