version: '3'
services:
    nginx:
        image: nginx:latest
        container_name: nginx_1
        ports:
            - 80:80
        restart: always
        networks:
            mynetwork:
                aliases:
                    - nginx
        volumes:
            - /home/docker/nginx/html:/usr/share/nginx/html
            - /home/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - /home/docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - /home/docker/nginx/logs:/var/log/nginx
            - /home/docker/nginx/web:/opt/nginx/web
networks:
    mynetwork:
        driver: bridge