/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zync_jni_api_MtkUsbJNI */

#ifndef _Included_com_zync_jni_api_MtkUsbJNI
#define _Included_com_zync_jni_api_MtkUsbJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zync_jni_api_MtkUsbJNI
 * Method:    scanDevice
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_zync_jni_api_MtkUsbJNI_scanDevice
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
