server:
  port: 8081

spring:
  application:
    name: seata-storage
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/seata_at_storage?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1qaz2wsx
  jpa:
    show-sql: true
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        namespace: 8b9bad7f-d58e-4f76-95f5-780aa8bdc9b3

# 以下内容拷贝(https://github.com/seata/seata/tree/develop/script/client/spring/application.yml)文件内容，并做相应修改
# 且要与seata server端的相应配置保持一致
seata:
  enabled: true
  # 需修改
  application-id: ${spring.application.name}
  # 事务群组（可以每个应用独立取名，也可以使用相同的名字）
  # 需修改（seata server端需添加配置: service.vgroupMapping.${spring.application.name}-tx-group=default）
  tx-service-group: ${spring.application.name}-tx-group
  enable-auto-data-source-proxy: true
  data-source-proxy-mode: AT
  use-jdk-proxy: false
  client:
    rm:
      # 异步提交缓存队列长度（默认10000）
      async-commit-buffer-limit: 10000
      # 一阶段结果上报TC重试次数（默认5）
      report-retry-count: 5
      # 自动刷新缓存中的表结构（默认false）
      table-meta-check-enable: false
      report-success-enable: false
      saga-branch-register-enable: false
      saga-json-parser: fastjson
      saga-retry-persist-mode-update: false
      saga-compensate-persist-mode-update: false
      lock:
        # 校验或占用全局锁重试间隔（默认10ms）
        retry-interval: 10
        # 校验或占用全局锁重试次数（默认30）
        retry-times: 30
        # 分支事务与其它全局回滚事务冲突时锁策略（优先释放本地锁让回滚成功）
        retry-policy-branch-rollback-on-conflict: true
    tm:
      # 一阶段全局提交结果上报TC重试次数（默认5次，建议大于1）
      commit-retry-count: 5
      # 一阶段全局回滚结果上报TC重试次数（默认5次，建议大于1）
      rollback-retry-count: 5
      default-global-transaction-timeout: 60000
      degrade-check: false
      degrade-check-period: 2000
      degrade-check-allow-times: 10
    undo:
      # 二阶段回滚镜像校验（默认true开启）
      data-validation: true
      # undo序列化方式（默认jackson）
      log-serialization: jackson
      # 自定义undo表名（默认undo_log）
      log-table: undo_log
      only-care-update-columns: true
      compress:
        enable: true
        type: zip
        threshold: 64k
    load-balance:
      type: RandomLoadBalance
      virtual-nodes: 10
  service:
    # 虚拟组和分组的映射, 需修改
    vgroup-mapping:
      # TC 集群（必须与seata-server保持一致, 也与seata.tx-service-group一致）
      seata-storage-tx-group: default
    # 分组和 seata 服务的映射, 需修改
    grouplist:
      default: 127.0.0.1:8091
    # 降级开关
    enable-degrade: false
    # 禁用全局事务（默认false）
    disable-global-transaction: false
  transport:
    shutdown:
      wait: 3
    thread-factory:
      boss-thread-prefix: NettyBoss
      worker-thread-prefix: NettyServerNIOWorker
      server-executor-thread-prefix: NettyServerBizHandler
      share-boss-worker: false
      client-selector-thread-prefix: NettyClientSelector
      client-selector-thread-size: 1
      client-worker-thread-prefix: NettyClientWorkerThread
      worker-thread-size: default
      boss-thread-size: 1
    type: TCP
    server: NIO
    heartbeat: true
    serialization: seata
    compressor: none
    # 客户端事务消息请求是否批量合并发送（默认true）
    enable-client-batch-send-request: true
  config:
    # 需修改
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      namespace: 8b9bad7f-d58e-4f76-95f5-780aa8bdc9b3
      group: SEATA_GROUP
      username: nacos
      password: nacos
  registry:
    # 需修改
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      namespace: 8b9bad7f-d58e-4f76-95f5-780aa8bdc9b3
      cluster: default
      username: nacos
      password: nacos
  log:
    # 日志异常输出概率（默认100）
    exception-rate: 100