spring:
  application:
    name: eureka-server
server:
  port: 8762
eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
    # 服务注册中心也会将自己作为客户端来尝试注册自己,为true（默认）时自动生效
    # 做注册中心集群的时候，必须设置为true

    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8763/eureka/